#!/usr/bin/env python3
"""Generate ``paper/generated/levels.tex`` from ``docs/data/levels.json``.

Keeps the paper's numbers sourced from the one canonical dataset (produced by
``python -m cryptocoma table``) so the article can never disagree with the library.

Run from anywhere:  ``python paper/gen_data.py``
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "docs" / "data" / "levels.json"
OUT = ROOT / "paper" / "generated" / "levels.tex"
TABLE_OUT = ROOT / "paper" / "generated" / "levels-table.tex"


def latex_escape(s: str) -> str:
    for a, b in [
        ("\\", r"\textbackslash "),
        ("&", r"\&"),
        ("%", r"\%"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("~", r"\textasciitilde "),
        ("^", r"\textasciicircum "),
    ]:
        s = s.replace(a, b)
    return s


def star_notation(stars: int) -> str:
    """LaTeX math for a★k (the star operator anchored on the base level a)."""
    if stars == 0:
        return r"$a$"
    return rf"$a^{{\star {stars}}}$"


def mag_to_latex(s: str) -> str:
    """Canonical magnitude string -> LaTeX math.

    Handles the plain, sci, and iterated-``10^(...)`` tower forms uniformly, e.g.
    ``"10^(10^(3.6e+37))"`` -> ``"10^{10^{3.6\\times10^{37}}}"``.
    """
    s = s.replace("10^(", "10^{").replace(")", "}")
    return re.sub(
        r"([0-9.]+)e\+?(-?[0-9]+)",
        lambda m: rf"{m.group(1).rstrip('.0') or '1'}\times10^{{{int(m.group(2))}}}",
        s,
    )


def write_levels_table(data: dict) -> None:
    """A full a…z table (star notation + the RU 'scale' line) — makes the paper less dry."""
    rows = []
    for lv in data["levels"]:
        note = latex_escape(lv["scale_hint"]["ru"])
        rows.append(rf"{lv['letter']} & {star_notation(lv['stars'])} & {note} \\")
    cc = data["crypto_coma"]
    rows.append(
        rf"$\ccoma$ & {star_notation(data['meta']['levels'])} & {latex_escape(cc['scale_hint']['ru'])} \\"
    )
    body = "\n".join(rows)
    TABLE_OUT.write_text(
        "% AUTO-GENERATED by paper/gen_data.py from docs/data/levels.json — do not edit.\n"
        "\\begin{longtable}{@{}c l p{8cm}@{}}\n"
        "\\toprule\n"
        "Ур. & Запись & Насколько это много \\\\\n"
        "\\midrule\n"
        "\\endhead\n"
        f"{body}\n"
        "\\bottomrule\n"
        "\\end{longtable}\n",
        encoding="utf-8",
    )
    print(f"wrote {TABLE_OUT}")


def main() -> int:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    meta = data["meta"]
    level_a = data["levels"][0]
    level_b = next(lv for lv in data["levels"] if lv["letter"] == "b")
    cc = data["crypto_coma"]

    anchor = int(meta["anchor_log10"])  # 36 — the 10^36 sub-base inside a
    lines = [
        "% AUTO-GENERATED by paper/gen_data.py from docs/data/levels.json — do not edit.",
        rf"\newcommand{{\nlevels}}{{{meta['levels']}}}",
        rf"\newcommand{{\anchorlog}}{{{anchor}}}",  # log10 of the 10^36 anchor
        rf"\newcommand{{\avalue}}{{(10^{{{anchor}}})^{{(10^{{{anchor}}})}}}}",  # base a
        rf"\newcommand{{\amagnitude}}{{{mag_to_latex(level_a['log10_str'])}}}",  # M(1)=log10(a)
        rf"\newcommand{{\bmagnitude}}{{{mag_to_latex(level_b['log10_str'])}}}",
        rf"\newcommand{{\bvalue}}{{{mag_to_latex(level_b['value_str'])}}}",
        rf"\newcommand{{\ccheight}}{{{cc['tower_height']}}}",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    write_levels_table(data)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
