#!/usr/bin/env python3
"""Generate ``paper/generated/levels.tex`` from ``docs/data/levels.json``.

Keeps the paper's numbers sourced from the one canonical dataset (produced by
``python -m cryptocoma table``) so the article can never disagree with the library.

Run from anywhere:  ``python paper/gen_data.py``
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "docs" / "data" / "levels.json"
OUT = ROOT / "paper" / "generated" / "levels.tex"
TABLE_OUT = ROOT / "paper" / "generated" / "levels-table.tex"


def latex_escape(s: str) -> str:
    for a, b in [
        ("\\", r"\textbackslash "),
        ("&", r"\&"),
        ("%", r"\%"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("~", r"\textasciitilde "),
        ("^", r"\textasciicircum "),
    ]:
        s = s.replace(a, b)
    return s


def star_notation(stars: int) -> str:
    """LaTeX math for (10^36)★k."""
    if stars == 0:
        return r"$10^{36}$"
    return rf"$(10^{{36}})^{{\star {stars}}}$"


def write_levels_table(data: dict) -> None:
    """A full a…z table (star notation + the RU 'scale' line) — makes the paper less dry."""
    rows = []
    for lv in data["levels"]:
        note = latex_escape(lv["scale_hint"]["ru"])
        rows.append(rf"{lv['letter']} & {star_notation(lv['stars'])} & {note} \\")
    cc = data["crypto_coma"]
    rows.append(
        rf"$\ccoma$ & {star_notation(data['meta']['levels'])} & {latex_escape(cc['scale_hint']['ru'])} \\"
    )
    body = "\n".join(rows)
    TABLE_OUT.write_text(
        "% AUTO-GENERATED by paper/gen_data.py from docs/data/levels.json — do not edit.\n"
        "\\begin{longtable}{@{}c l p{8cm}@{}}\n"
        "\\toprule\n"
        "Ур. & Запись & Насколько это много \\\\\n"
        "\\midrule\n"
        "\\endhead\n"
        f"{body}\n"
        "\\bottomrule\n"
        "\\end{longtable}\n",
        encoding="utf-8",
    )
    print(f"wrote {TABLE_OUT}")


def sci_to_latex(s: str) -> str:
    """'3.6e+37' -> '3.6\\times10^{37}' ; plain ints pass through."""
    m = re.fullmatch(r"([0-9.]+)e\+?(-?[0-9]+)", s.strip())
    if not m:
        return s
    mant, exp = m.group(1), int(m.group(2))
    mant = mant.rstrip(".0") or "1"
    return rf"{mant}\times10^{{{int(exp)}}}"


def main() -> int:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    meta = data["meta"]
    level_b = next(lv for lv in data["levels"] if lv["letter"] == "b")
    cc = data["crypto_coma"]

    lines = [
        "% AUTO-GENERATED by paper/gen_data.py from docs/data/levels.json — do not edit.",
        rf"\newcommand{{\nlevels}}{{{meta['levels']}}}",
        rf"\newcommand{{\startlog}}{{{int(meta['start_value_log10'])}}}",
        rf"\newcommand{{\avalue}}{{10^{{{int(meta['start_value_log10'])}}}}}",
        rf"\newcommand{{\bmagnitude}}{{{sci_to_latex(level_b['log10_str'])}}}",
        rf"\newcommand{{\bvalue}}{{10^{{{sci_to_latex(level_b['log10_str'])}}}}}",
        rf"\newcommand{{\ccheight}}{{{cc['tower_height']}}}",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    write_levels_table(data)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
